// Code generated by protoc-gen-go. DO NOT EDIT.
// source: values.proto

package values

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Values struct {
	ValueMap             map[string]*Values_Value `protobuf:"bytes,1,rep,name=value_map,json=valueMap,proto3" json:"value_map,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0}
}

func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetValueMap() map[string]*Values_Value {
	if m != nil {
		return m.ValueMap
	}
	return nil
}

// Specifies one value with different types possible.
type Values_Value struct {
	// The attribute value.
	//
	// Types that are valid to be assigned to Value:
	//	*Values_Value_StringValue
	//	*Values_Value_StringList
	//	*Values_Value_Int64Value
	//	*Values_Value_Int64List
	//	*Values_Value_DoubleValue
	//	*Values_Value_DoubleList
	//	*Values_Value_BoolValue
	//	*Values_Value_BoolList
	//	*Values_Value_BytesValue
	//	*Values_Value_TimestampValue
	//	*Values_Value_TimestampList
	//	*Values_Value_DurationValue
	//	*Values_Value_DurationList
	Value                isValues_Value_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Values_Value) Reset()         { *m = Values_Value{} }
func (m *Values_Value) String() string { return proto.CompactTextString(m) }
func (*Values_Value) ProtoMessage()    {}
func (*Values_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 1}
}

func (m *Values_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_Value.Unmarshal(m, b)
}
func (m *Values_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_Value.Marshal(b, m, deterministic)
}
func (m *Values_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_Value.Merge(m, src)
}
func (m *Values_Value) XXX_Size() int {
	return xxx_messageInfo_Values_Value.Size(m)
}
func (m *Values_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Values_Value proto.InternalMessageInfo

type isValues_Value_Value interface {
	isValues_Value_Value()
}

type Values_Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Values_Value_StringList struct {
	StringList *Values_StringList `protobuf:"bytes,2,opt,name=string_list,json=stringList,proto3,oneof"`
}

type Values_Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Values_Value_Int64List struct {
	Int64List *Values_Int64List `protobuf:"bytes,4,opt,name=int64_list,json=int64List,proto3,oneof"`
}

type Values_Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Values_Value_DoubleList struct {
	DoubleList *Values_DoubleList `protobuf:"bytes,6,opt,name=double_list,json=doubleList,proto3,oneof"`
}

type Values_Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Values_Value_BoolList struct {
	BoolList *Values_BoolList `protobuf:"bytes,8,opt,name=bool_list,json=boolList,proto3,oneof"`
}

type Values_Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Values_Value_TimestampValue struct {
	TimestampValue *timestamp.Timestamp `protobuf:"bytes,10,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Values_Value_TimestampList struct {
	TimestampList *Values_TimestampList `protobuf:"bytes,11,opt,name=timestamp_list,json=timestampList,proto3,oneof"`
}

type Values_Value_DurationValue struct {
	DurationValue *duration.Duration `protobuf:"bytes,12,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type Values_Value_DurationList struct {
	DurationList *Values_DurationList `protobuf:"bytes,13,opt,name=duration_list,json=durationList,proto3,oneof"`
}

func (*Values_Value_StringValue) isValues_Value_Value() {}

func (*Values_Value_StringList) isValues_Value_Value() {}

func (*Values_Value_Int64Value) isValues_Value_Value() {}

func (*Values_Value_Int64List) isValues_Value_Value() {}

func (*Values_Value_DoubleValue) isValues_Value_Value() {}

func (*Values_Value_DoubleList) isValues_Value_Value() {}

func (*Values_Value_BoolValue) isValues_Value_Value() {}

func (*Values_Value_BoolList) isValues_Value_Value() {}

func (*Values_Value_BytesValue) isValues_Value_Value() {}

func (*Values_Value_TimestampValue) isValues_Value_Value() {}

func (*Values_Value_TimestampList) isValues_Value_Value() {}

func (*Values_Value_DurationValue) isValues_Value_Value() {}

func (*Values_Value_DurationList) isValues_Value_Value() {}

func (m *Values_Value) GetValue() isValues_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Values_Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Values_Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Values_Value) GetStringList() *Values_StringList {
	if x, ok := m.GetValue().(*Values_Value_StringList); ok {
		return x.StringList
	}
	return nil
}

func (m *Values_Value) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*Values_Value_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

func (m *Values_Value) GetInt64List() *Values_Int64List {
	if x, ok := m.GetValue().(*Values_Value_Int64List); ok {
		return x.Int64List
	}
	return nil
}

func (m *Values_Value) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Values_Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Values_Value) GetDoubleList() *Values_DoubleList {
	if x, ok := m.GetValue().(*Values_Value_DoubleList); ok {
		return x.DoubleList
	}
	return nil
}

func (m *Values_Value) GetBoolValue() bool {
	if x, ok := m.GetValue().(*Values_Value_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (m *Values_Value) GetBoolList() *Values_BoolList {
	if x, ok := m.GetValue().(*Values_Value_BoolList); ok {
		return x.BoolList
	}
	return nil
}

func (m *Values_Value) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*Values_Value_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *Values_Value) GetTimestampValue() *timestamp.Timestamp {
	if x, ok := m.GetValue().(*Values_Value_TimestampValue); ok {
		return x.TimestampValue
	}
	return nil
}

func (m *Values_Value) GetTimestampList() *Values_TimestampList {
	if x, ok := m.GetValue().(*Values_Value_TimestampList); ok {
		return x.TimestampList
	}
	return nil
}

func (m *Values_Value) GetDurationValue() *duration.Duration {
	if x, ok := m.GetValue().(*Values_Value_DurationValue); ok {
		return x.DurationValue
	}
	return nil
}

func (m *Values_Value) GetDurationList() *Values_DurationList {
	if x, ok := m.GetValue().(*Values_Value_DurationList); ok {
		return x.DurationList
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Values_Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Values_Value_StringValue)(nil),
		(*Values_Value_StringList)(nil),
		(*Values_Value_Int64Value)(nil),
		(*Values_Value_Int64List)(nil),
		(*Values_Value_DoubleValue)(nil),
		(*Values_Value_DoubleList)(nil),
		(*Values_Value_BoolValue)(nil),
		(*Values_Value_BoolList)(nil),
		(*Values_Value_BytesValue)(nil),
		(*Values_Value_TimestampValue)(nil),
		(*Values_Value_TimestampList)(nil),
		(*Values_Value_DurationValue)(nil),
		(*Values_Value_DurationList)(nil),
	}
}

type Values_StringList struct {
	Items                []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Values_StringList) Reset()         { *m = Values_StringList{} }
func (m *Values_StringList) String() string { return proto.CompactTextString(m) }
func (*Values_StringList) ProtoMessage()    {}
func (*Values_StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 2}
}

func (m *Values_StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_StringList.Unmarshal(m, b)
}
func (m *Values_StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_StringList.Marshal(b, m, deterministic)
}
func (m *Values_StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_StringList.Merge(m, src)
}
func (m *Values_StringList) XXX_Size() int {
	return xxx_messageInfo_Values_StringList.Size(m)
}
func (m *Values_StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_Values_StringList proto.InternalMessageInfo

func (m *Values_StringList) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type Values_Int64List struct {
	Items                []int64  `protobuf:"varint,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Values_Int64List) Reset()         { *m = Values_Int64List{} }
func (m *Values_Int64List) String() string { return proto.CompactTextString(m) }
func (*Values_Int64List) ProtoMessage()    {}
func (*Values_Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 3}
}

func (m *Values_Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_Int64List.Unmarshal(m, b)
}
func (m *Values_Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_Int64List.Marshal(b, m, deterministic)
}
func (m *Values_Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_Int64List.Merge(m, src)
}
func (m *Values_Int64List) XXX_Size() int {
	return xxx_messageInfo_Values_Int64List.Size(m)
}
func (m *Values_Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Values_Int64List proto.InternalMessageInfo

func (m *Values_Int64List) GetItems() []int64 {
	if m != nil {
		return m.Items
	}
	return nil
}

type Values_DoubleList struct {
	Items                []float64 `protobuf:"fixed64,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Values_DoubleList) Reset()         { *m = Values_DoubleList{} }
func (m *Values_DoubleList) String() string { return proto.CompactTextString(m) }
func (*Values_DoubleList) ProtoMessage()    {}
func (*Values_DoubleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 4}
}

func (m *Values_DoubleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_DoubleList.Unmarshal(m, b)
}
func (m *Values_DoubleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_DoubleList.Marshal(b, m, deterministic)
}
func (m *Values_DoubleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_DoubleList.Merge(m, src)
}
func (m *Values_DoubleList) XXX_Size() int {
	return xxx_messageInfo_Values_DoubleList.Size(m)
}
func (m *Values_DoubleList) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_DoubleList.DiscardUnknown(m)
}

var xxx_messageInfo_Values_DoubleList proto.InternalMessageInfo

func (m *Values_DoubleList) GetItems() []float64 {
	if m != nil {
		return m.Items
	}
	return nil
}

type Values_BoolList struct {
	Items                []bool   `protobuf:"varint,1,rep,packed,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Values_BoolList) Reset()         { *m = Values_BoolList{} }
func (m *Values_BoolList) String() string { return proto.CompactTextString(m) }
func (*Values_BoolList) ProtoMessage()    {}
func (*Values_BoolList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 5}
}

func (m *Values_BoolList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_BoolList.Unmarshal(m, b)
}
func (m *Values_BoolList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_BoolList.Marshal(b, m, deterministic)
}
func (m *Values_BoolList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_BoolList.Merge(m, src)
}
func (m *Values_BoolList) XXX_Size() int {
	return xxx_messageInfo_Values_BoolList.Size(m)
}
func (m *Values_BoolList) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_BoolList.DiscardUnknown(m)
}

var xxx_messageInfo_Values_BoolList proto.InternalMessageInfo

func (m *Values_BoolList) GetItems() []bool {
	if m != nil {
		return m.Items
	}
	return nil
}

type Values_TimestampList struct {
	Items                []*timestamp.Timestamp `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Values_TimestampList) Reset()         { *m = Values_TimestampList{} }
func (m *Values_TimestampList) String() string { return proto.CompactTextString(m) }
func (*Values_TimestampList) ProtoMessage()    {}
func (*Values_TimestampList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 6}
}

func (m *Values_TimestampList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_TimestampList.Unmarshal(m, b)
}
func (m *Values_TimestampList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_TimestampList.Marshal(b, m, deterministic)
}
func (m *Values_TimestampList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_TimestampList.Merge(m, src)
}
func (m *Values_TimestampList) XXX_Size() int {
	return xxx_messageInfo_Values_TimestampList.Size(m)
}
func (m *Values_TimestampList) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_TimestampList.DiscardUnknown(m)
}

var xxx_messageInfo_Values_TimestampList proto.InternalMessageInfo

func (m *Values_TimestampList) GetItems() []*timestamp.Timestamp {
	if m != nil {
		return m.Items
	}
	return nil
}

type Values_DurationList struct {
	Items                []*duration.Duration `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Values_DurationList) Reset()         { *m = Values_DurationList{} }
func (m *Values_DurationList) String() string { return proto.CompactTextString(m) }
func (*Values_DurationList) ProtoMessage()    {}
func (*Values_DurationList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d19e76c3b90e014, []int{0, 7}
}

func (m *Values_DurationList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values_DurationList.Unmarshal(m, b)
}
func (m *Values_DurationList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values_DurationList.Marshal(b, m, deterministic)
}
func (m *Values_DurationList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values_DurationList.Merge(m, src)
}
func (m *Values_DurationList) XXX_Size() int {
	return xxx_messageInfo_Values_DurationList.Size(m)
}
func (m *Values_DurationList) XXX_DiscardUnknown() {
	xxx_messageInfo_Values_DurationList.DiscardUnknown(m)
}

var xxx_messageInfo_Values_DurationList proto.InternalMessageInfo

func (m *Values_DurationList) GetItems() []*duration.Duration {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Values)(nil), "values.Values")
	proto.RegisterMapType((map[string]*Values_Value)(nil), "values.Values.ValueMapEntry")
	proto.RegisterType((*Values_Value)(nil), "values.Values.Value")
	proto.RegisterType((*Values_StringList)(nil), "values.Values.StringList")
	proto.RegisterType((*Values_Int64List)(nil), "values.Values.Int64List")
	proto.RegisterType((*Values_DoubleList)(nil), "values.Values.DoubleList")
	proto.RegisterType((*Values_BoolList)(nil), "values.Values.BoolList")
	proto.RegisterType((*Values_TimestampList)(nil), "values.Values.TimestampList")
	proto.RegisterType((*Values_DurationList)(nil), "values.Values.DurationList")
}

func init() { proto.RegisterFile("values.proto", fileDescriptor_5d19e76c3b90e014) }

var fileDescriptor_5d19e76c3b90e014 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x5f, 0x8b, 0xd3, 0x4c,
	0x14, 0xc6, 0x3b, 0xdb, 0xb7, 0xdd, 0xe4, 0x34, 0xdd, 0x57, 0x86, 0x05, 0x6b, 0x14, 0x37, 0x5b,
	0x11, 0x83, 0x17, 0xa9, 0xac, 0xb2, 0xb8, 0x22, 0x88, 0x65, 0x17, 0x2a, 0xe8, 0x85, 0x51, 0xf6,
	0xc2, 0x9b, 0x92, 0xd8, 0x58, 0xc3, 0xa6, 0x9d, 0x90, 0x4c, 0x16, 0xfa, 0x05, 0xfd, 0x3c, 0x7e,
	0x04, 0x99, 0x39, 0x67, 0xd2, 0x24, 0xac, 0xde, 0xb4, 0x79, 0x4e, 0x9e, 0xfc, 0xce, 0x9f, 0x39,
	0x09, 0x38, 0xb7, 0x51, 0x56, 0x25, 0x65, 0x90, 0x17, 0x42, 0x0a, 0x3e, 0x44, 0xe5, 0x3e, 0x5e,
	0x0b, 0xb1, 0xce, 0x92, 0x99, 0x8e, 0xc6, 0xd5, 0x8f, 0xd9, 0xaa, 0x2a, 0x22, 0x99, 0x8a, 0x2d,
	0xfa, 0xdc, 0x93, 0xee, 0x7d, 0x99, 0x6e, 0x92, 0x52, 0x46, 0x9b, 0x1c, 0x0d, 0xd3, 0xdf, 0x16,
	0x0c, 0xaf, 0x35, 0x8b, 0x5f, 0x80, 0xad, 0xa9, 0xcb, 0x4d, 0x94, 0x4f, 0x98, 0xd7, 0xf7, 0x47,
	0x67, 0x8f, 0x02, 0xca, 0x7a, 0xdd, 0xf8, 0xfb, 0x14, 0xe5, 0x57, 0x5b, 0x59, 0xec, 0x42, 0xeb,
	0x96, 0xa4, 0xfb, 0x19, 0xc6, 0xad, 0x5b, 0xfc, 0x1e, 0xf4, 0x6f, 0x92, 0xdd, 0x84, 0x79, 0xcc,
	0xb7, 0x43, 0x75, 0xc9, 0x9f, 0xc3, 0x40, 0xdb, 0x27, 0x07, 0x1e, 0xf3, 0x47, 0x67, 0xc7, 0x77,
	0x91, 0x43, 0xb4, 0xbc, 0x39, 0x78, 0xcd, 0xdc, 0x5f, 0x03, 0x18, 0xe8, 0x20, 0x7f, 0x02, 0x4e,
	0x29, 0x8b, 0x74, 0xbb, 0x5e, 0x22, 0x40, 0x43, 0x17, 0xbd, 0x70, 0x84, 0x51, 0x34, 0xbd, 0x05,
	0x92, 0xcb, 0x2c, 0x2d, 0x25, 0x25, 0x79, 0xd0, 0x49, 0xf2, 0x45, 0x3b, 0x3e, 0xa6, 0xa5, 0x5c,
	0xf4, 0x42, 0x28, 0x6b, 0xc5, 0x4f, 0x61, 0x94, 0x6e, 0xe5, 0xf9, 0x2b, 0xca, 0xd0, 0xf7, 0x98,
	0xdf, 0x57, 0x16, 0x1d, 0xc4, 0x04, 0x17, 0x80, 0x0a, 0xf9, 0xff, 0x69, 0xfe, 0xa4, 0xc3, 0xff,
	0xa0, 0x0c, 0x84, 0xb7, 0x53, 0x23, 0x54, 0x03, 0x2b, 0x51, 0xc5, 0x59, 0x42, 0xf8, 0x81, 0xc7,
	0x7c, 0xa6, 0x1a, 0xc0, 0x68, 0xdd, 0x00, 0x99, 0x74, 0x82, 0xe1, 0x9d, 0x0d, 0x5c, 0x6a, 0x87,
	0x69, 0x60, 0x55, 0x2b, 0x7e, 0x02, 0x10, 0x0b, 0x91, 0x51, 0x82, 0x43, 0x8f, 0xf9, 0x96, 0xaa,
	0x41, 0xc5, 0x10, 0x7f, 0x0e, 0x5a, 0x20, 0xdc, 0xd2, 0xf0, 0xfb, 0x1d, 0xf8, 0x5c, 0x88, 0x8c,
	0xd0, 0x56, 0x4c, 0xd7, 0x6a, 0x32, 0xf1, 0x4e, 0x26, 0x25, 0x91, 0x6d, 0x8f, 0xf9, 0x8e, 0xca,
	0xad, 0x83, 0x88, 0xbe, 0x82, 0xff, 0xeb, 0xad, 0x22, 0x1b, 0xe8, 0x04, 0x6e, 0x80, 0xdb, 0x17,
	0x98, 0xed, 0x0b, 0xbe, 0x1a, 0xdf, 0xa2, 0x17, 0x1e, 0xd5, 0x0f, 0x19, 0xcc, 0x3e, 0x82, 0x65,
	0x8e, 0x34, 0xa5, 0xbb, 0x83, 0x35, 0x83, 0x6a, 0x1d, 0xcb, 0x66, 0x80, 0xcf, 0xe1, 0xc8, 0xbc,
	0x03, 0x54, 0x8c, 0x43, 0xa3, 0xec, 0x16, 0x73, 0x49, 0x36, 0xc5, 0x30, 0x8f, 0x60, 0x29, 0x73,
	0xa8, 0x03, 0x58, 0xc9, 0x58, 0x23, 0x1e, 0x76, 0x4f, 0x83, 0x3c, 0x54, 0x88, 0xb3, 0x6a, 0xe8,
	0xf9, 0x21, 0xed, 0xbb, 0x3b, 0x05, 0xd8, 0xef, 0x1d, 0x3f, 0x86, 0x41, 0x2a, 0x93, 0x4d, 0xa9,
	0x5f, 0x30, 0x3b, 0x44, 0xe1, 0x9e, 0x82, 0x5d, 0xef, 0x4e, 0xdb, 0xd2, 0x37, 0x96, 0x29, 0xc0,
	0xfe, 0xf4, 0xdb, 0x1e, 0x66, 0x3c, 0x1e, 0x58, 0xe6, 0x10, 0xdb, 0x0e, 0xcb, 0x38, 0xde, 0xc3,
	0xb8, 0x35, 0x3f, 0xfe, 0xa2, 0x69, 0xfb, 0xe7, 0x91, 0x19, 0xc4, 0x3b, 0x70, 0x9a, 0x8d, 0xf3,
	0x59, 0x9b, 0xf0, 0xf7, 0x39, 0x13, 0x60, 0xfe, 0xec, 0xdb, 0xd3, 0x75, 0x2a, 0x7f, 0x56, 0x71,
	0xf0, 0x5d, 0x6c, 0x66, 0xab, 0x28, 0x2f, 0xf0, 0x27, 0xbf, 0x59, 0xe3, 0x77, 0x6a, 0x86, 0x63,
	0x8e, 0x87, 0x5a, 0xbd, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x41, 0x27, 0xdf, 0xd1, 0xfb, 0x04,
	0x00, 0x00,
}
