// Code generated by protoc-gen-go. DO NOT EDIT.
// source: daprinternal.proto

package daprinternal

import (
	context "context"
	fmt "fmt"
	values "github.com/dapr/dapr/pkg/proto/values"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocalCallEnvelope struct {
	Data                 *any.Any          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LocalCallEnvelope) Reset()         { *m = LocalCallEnvelope{} }
func (m *LocalCallEnvelope) String() string { return proto.CompactTextString(m) }
func (*LocalCallEnvelope) ProtoMessage()    {}
func (*LocalCallEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{0}
}

func (m *LocalCallEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalCallEnvelope.Unmarshal(m, b)
}
func (m *LocalCallEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalCallEnvelope.Marshal(b, m, deterministic)
}
func (m *LocalCallEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalCallEnvelope.Merge(m, src)
}
func (m *LocalCallEnvelope) XXX_Size() int {
	return xxx_messageInfo_LocalCallEnvelope.Size(m)
}
func (m *LocalCallEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalCallEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_LocalCallEnvelope proto.InternalMessageInfo

func (m *LocalCallEnvelope) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LocalCallEnvelope) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *LocalCallEnvelope) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CallActorEnvelope struct {
	ActorID              string            `protobuf:"bytes,1,opt,name=actorID,proto3" json:"actorID,omitempty"`
	ActorType            string            `protobuf:"bytes,2,opt,name=actorType,proto3" json:"actorType,omitempty"`
	Method               string            `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Data                 *any.Any          `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CallActorEnvelope) Reset()         { *m = CallActorEnvelope{} }
func (m *CallActorEnvelope) String() string { return proto.CompactTextString(m) }
func (*CallActorEnvelope) ProtoMessage()    {}
func (*CallActorEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{1}
}

func (m *CallActorEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CallActorEnvelope.Unmarshal(m, b)
}
func (m *CallActorEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CallActorEnvelope.Marshal(b, m, deterministic)
}
func (m *CallActorEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallActorEnvelope.Merge(m, src)
}
func (m *CallActorEnvelope) XXX_Size() int {
	return xxx_messageInfo_CallActorEnvelope.Size(m)
}
func (m *CallActorEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_CallActorEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_CallActorEnvelope proto.InternalMessageInfo

func (m *CallActorEnvelope) GetActorID() string {
	if m != nil {
		return m.ActorID
	}
	return ""
}

func (m *CallActorEnvelope) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *CallActorEnvelope) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallActorEnvelope) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CallActorEnvelope) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type InvokeResponse struct {
	Data                 *any.Any          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{2}
}

func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (m *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(m, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetData() *any.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InvokeResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Component struct {
	Metadata             *ComponentMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec                 *ComponentSpec     `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Auth                 *ComponentAuth     `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{3}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetMetadata() *ComponentMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Component) GetSpec() *ComponentSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Component) GetAuth() *ComponentAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type ComponentMetadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentMetadata) Reset()         { *m = ComponentMetadata{} }
func (m *ComponentMetadata) String() string { return proto.CompactTextString(m) }
func (*ComponentMetadata) ProtoMessage()    {}
func (*ComponentMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{4}
}

func (m *ComponentMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentMetadata.Unmarshal(m, b)
}
func (m *ComponentMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentMetadata.Marshal(b, m, deterministic)
}
func (m *ComponentMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentMetadata.Merge(m, src)
}
func (m *ComponentMetadata) XXX_Size() int {
	return xxx_messageInfo_ComponentMetadata.Size(m)
}
func (m *ComponentMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentMetadata proto.InternalMessageInfo

func (m *ComponentMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComponentMetadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ComponentSpec struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Config               *values.Values `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ComponentSpec) Reset()         { *m = ComponentSpec{} }
func (m *ComponentSpec) String() string { return proto.CompactTextString(m) }
func (*ComponentSpec) ProtoMessage()    {}
func (*ComponentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{5}
}

func (m *ComponentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentSpec.Unmarshal(m, b)
}
func (m *ComponentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentSpec.Marshal(b, m, deterministic)
}
func (m *ComponentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentSpec.Merge(m, src)
}
func (m *ComponentSpec) XXX_Size() int {
	return xxx_messageInfo_ComponentSpec.Size(m)
}
func (m *ComponentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentSpec proto.InternalMessageInfo

func (m *ComponentSpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ComponentSpec) GetConfig() *values.Values {
	if m != nil {
		return m.Config
	}
	return nil
}

type ComponentMetadataItem struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	SecretKeyRef         *ComponentSecretKeyRef `protobuf:"bytes,3,opt,name=secretKeyRef,proto3" json:"secretKeyRef,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ComponentMetadataItem) Reset()         { *m = ComponentMetadataItem{} }
func (m *ComponentMetadataItem) String() string { return proto.CompactTextString(m) }
func (*ComponentMetadataItem) ProtoMessage()    {}
func (*ComponentMetadataItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{6}
}

func (m *ComponentMetadataItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentMetadataItem.Unmarshal(m, b)
}
func (m *ComponentMetadataItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentMetadataItem.Marshal(b, m, deterministic)
}
func (m *ComponentMetadataItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentMetadataItem.Merge(m, src)
}
func (m *ComponentMetadataItem) XXX_Size() int {
	return xxx_messageInfo_ComponentMetadataItem.Size(m)
}
func (m *ComponentMetadataItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentMetadataItem.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentMetadataItem proto.InternalMessageInfo

func (m *ComponentMetadataItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComponentMetadataItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ComponentMetadataItem) GetSecretKeyRef() *ComponentSecretKeyRef {
	if m != nil {
		return m.SecretKeyRef
	}
	return nil
}

type ComponentSecretKeyRef struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentSecretKeyRef) Reset()         { *m = ComponentSecretKeyRef{} }
func (m *ComponentSecretKeyRef) String() string { return proto.CompactTextString(m) }
func (*ComponentSecretKeyRef) ProtoMessage()    {}
func (*ComponentSecretKeyRef) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{7}
}

func (m *ComponentSecretKeyRef) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentSecretKeyRef.Unmarshal(m, b)
}
func (m *ComponentSecretKeyRef) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentSecretKeyRef.Marshal(b, m, deterministic)
}
func (m *ComponentSecretKeyRef) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentSecretKeyRef.Merge(m, src)
}
func (m *ComponentSecretKeyRef) XXX_Size() int {
	return xxx_messageInfo_ComponentSecretKeyRef.Size(m)
}
func (m *ComponentSecretKeyRef) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentSecretKeyRef.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentSecretKeyRef proto.InternalMessageInfo

func (m *ComponentSecretKeyRef) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ComponentSecretKeyRef) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ComponentAuth struct {
	SecretStore          string   `protobuf:"bytes,1,opt,name=secretStore,proto3" json:"secretStore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComponentAuth) Reset()         { *m = ComponentAuth{} }
func (m *ComponentAuth) String() string { return proto.CompactTextString(m) }
func (*ComponentAuth) ProtoMessage()    {}
func (*ComponentAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{8}
}

func (m *ComponentAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComponentAuth.Unmarshal(m, b)
}
func (m *ComponentAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComponentAuth.Marshal(b, m, deterministic)
}
func (m *ComponentAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComponentAuth.Merge(m, src)
}
func (m *ComponentAuth) XXX_Size() int {
	return xxx_messageInfo_ComponentAuth.Size(m)
}
func (m *ComponentAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_ComponentAuth.DiscardUnknown(m)
}

var xxx_messageInfo_ComponentAuth proto.InternalMessageInfo

func (m *ComponentAuth) GetSecretStore() string {
	if m != nil {
		return m.SecretStore
	}
	return ""
}

type SaveStateEnvelope struct {
	State                []*KeyVal `protobuf:"bytes,1,rep,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SaveStateEnvelope) Reset()         { *m = SaveStateEnvelope{} }
func (m *SaveStateEnvelope) String() string { return proto.CompactTextString(m) }
func (*SaveStateEnvelope) ProtoMessage()    {}
func (*SaveStateEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{9}
}

func (m *SaveStateEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveStateEnvelope.Unmarshal(m, b)
}
func (m *SaveStateEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveStateEnvelope.Marshal(b, m, deterministic)
}
func (m *SaveStateEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveStateEnvelope.Merge(m, src)
}
func (m *SaveStateEnvelope) XXX_Size() int {
	return xxx_messageInfo_SaveStateEnvelope.Size(m)
}
func (m *SaveStateEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveStateEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_SaveStateEnvelope proto.InternalMessageInfo

func (m *SaveStateEnvelope) GetState() []*KeyVal {
	if m != nil {
		return m.State
	}
	return nil
}

type KeyVal struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyVal) Reset()         { *m = KeyVal{} }
func (m *KeyVal) String() string { return proto.CompactTextString(m) }
func (*KeyVal) ProtoMessage()    {}
func (*KeyVal) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{10}
}

func (m *KeyVal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyVal.Unmarshal(m, b)
}
func (m *KeyVal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyVal.Marshal(b, m, deterministic)
}
func (m *KeyVal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyVal.Merge(m, src)
}
func (m *KeyVal) XXX_Size() int {
	return xxx_messageInfo_KeyVal.Size(m)
}
func (m *KeyVal) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyVal.DiscardUnknown(m)
}

var xxx_messageInfo_KeyVal proto.InternalMessageInfo

func (m *KeyVal) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyVal) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type GetStateEnvelope struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStateEnvelope) Reset()         { *m = GetStateEnvelope{} }
func (m *GetStateEnvelope) String() string { return proto.CompactTextString(m) }
func (*GetStateEnvelope) ProtoMessage()    {}
func (*GetStateEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{11}
}

func (m *GetStateEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateEnvelope.Unmarshal(m, b)
}
func (m *GetStateEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateEnvelope.Marshal(b, m, deterministic)
}
func (m *GetStateEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateEnvelope.Merge(m, src)
}
func (m *GetStateEnvelope) XXX_Size() int {
	return xxx_messageInfo_GetStateEnvelope.Size(m)
}
func (m *GetStateEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateEnvelope proto.InternalMessageInfo

func (m *GetStateEnvelope) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type PlacementOrder struct {
	Tables               *PlacementTables `protobuf:"bytes,1,opt,name=tables,proto3" json:"tables,omitempty"`
	Operation            string           `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PlacementOrder) Reset()         { *m = PlacementOrder{} }
func (m *PlacementOrder) String() string { return proto.CompactTextString(m) }
func (*PlacementOrder) ProtoMessage()    {}
func (*PlacementOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{12}
}

func (m *PlacementOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementOrder.Unmarshal(m, b)
}
func (m *PlacementOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementOrder.Marshal(b, m, deterministic)
}
func (m *PlacementOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementOrder.Merge(m, src)
}
func (m *PlacementOrder) XXX_Size() int {
	return xxx_messageInfo_PlacementOrder.Size(m)
}
func (m *PlacementOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementOrder proto.InternalMessageInfo

func (m *PlacementOrder) GetTables() *PlacementTables {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *PlacementOrder) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

type PlacementTables struct {
	Entries              map[string]*PlacementTable `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Version              string                     `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PlacementTables) Reset()         { *m = PlacementTables{} }
func (m *PlacementTables) String() string { return proto.CompactTextString(m) }
func (*PlacementTables) ProtoMessage()    {}
func (*PlacementTables) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{13}
}

func (m *PlacementTables) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementTables.Unmarshal(m, b)
}
func (m *PlacementTables) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementTables.Marshal(b, m, deterministic)
}
func (m *PlacementTables) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementTables.Merge(m, src)
}
func (m *PlacementTables) XXX_Size() int {
	return xxx_messageInfo_PlacementTables.Size(m)
}
func (m *PlacementTables) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementTables.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementTables proto.InternalMessageInfo

func (m *PlacementTables) GetEntries() map[string]*PlacementTable {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *PlacementTables) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PlacementTable struct {
	Hosts                map[uint64]string `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SortedSet            []uint64          `protobuf:"varint,2,rep,packed,name=sortedSet,proto3" json:"sortedSet,omitempty"`
	LoadMap              map[string]*Host  `protobuf:"bytes,3,rep,name=loadMap,proto3" json:"loadMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TotalLoad            int64             `protobuf:"varint,4,opt,name=totalLoad,proto3" json:"totalLoad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PlacementTable) Reset()         { *m = PlacementTable{} }
func (m *PlacementTable) String() string { return proto.CompactTextString(m) }
func (*PlacementTable) ProtoMessage()    {}
func (*PlacementTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{14}
}

func (m *PlacementTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlacementTable.Unmarshal(m, b)
}
func (m *PlacementTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlacementTable.Marshal(b, m, deterministic)
}
func (m *PlacementTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlacementTable.Merge(m, src)
}
func (m *PlacementTable) XXX_Size() int {
	return xxx_messageInfo_PlacementTable.Size(m)
}
func (m *PlacementTable) XXX_DiscardUnknown() {
	xxx_messageInfo_PlacementTable.DiscardUnknown(m)
}

var xxx_messageInfo_PlacementTable proto.InternalMessageInfo

func (m *PlacementTable) GetHosts() map[uint64]string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *PlacementTable) GetSortedSet() []uint64 {
	if m != nil {
		return m.SortedSet
	}
	return nil
}

func (m *PlacementTable) GetLoadMap() map[string]*Host {
	if m != nil {
		return m.LoadMap
	}
	return nil
}

func (m *PlacementTable) GetTotalLoad() int64 {
	if m != nil {
		return m.TotalLoad
	}
	return 0
}

type Host struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port                 int64    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Load                 int64    `protobuf:"varint,3,opt,name=load,proto3" json:"load,omitempty"`
	Entities             []string `protobuf:"bytes,4,rep,name=entities,proto3" json:"entities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Host) Reset()         { *m = Host{} }
func (m *Host) String() string { return proto.CompactTextString(m) }
func (*Host) ProtoMessage()    {}
func (*Host) Descriptor() ([]byte, []int) {
	return fileDescriptor_50527238b0452f75, []int{15}
}

func (m *Host) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Host.Unmarshal(m, b)
}
func (m *Host) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Host.Marshal(b, m, deterministic)
}
func (m *Host) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Host.Merge(m, src)
}
func (m *Host) XXX_Size() int {
	return xxx_messageInfo_Host.Size(m)
}
func (m *Host) XXX_DiscardUnknown() {
	xxx_messageInfo_Host.DiscardUnknown(m)
}

var xxx_messageInfo_Host proto.InternalMessageInfo

func (m *Host) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Host) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Host) GetLoad() int64 {
	if m != nil {
		return m.Load
	}
	return 0
}

func (m *Host) GetEntities() []string {
	if m != nil {
		return m.Entities
	}
	return nil
}

func init() {
	proto.RegisterType((*LocalCallEnvelope)(nil), "daprinternal.LocalCallEnvelope")
	proto.RegisterMapType((map[string]string)(nil), "daprinternal.LocalCallEnvelope.MetadataEntry")
	proto.RegisterType((*CallActorEnvelope)(nil), "daprinternal.CallActorEnvelope")
	proto.RegisterMapType((map[string]string)(nil), "daprinternal.CallActorEnvelope.MetadataEntry")
	proto.RegisterType((*InvokeResponse)(nil), "daprinternal.InvokeResponse")
	proto.RegisterMapType((map[string]string)(nil), "daprinternal.InvokeResponse.MetadataEntry")
	proto.RegisterType((*Component)(nil), "daprinternal.Component")
	proto.RegisterType((*ComponentMetadata)(nil), "daprinternal.ComponentMetadata")
	proto.RegisterType((*ComponentSpec)(nil), "daprinternal.ComponentSpec")
	proto.RegisterType((*ComponentMetadataItem)(nil), "daprinternal.ComponentMetadataItem")
	proto.RegisterType((*ComponentSecretKeyRef)(nil), "daprinternal.ComponentSecretKeyRef")
	proto.RegisterType((*ComponentAuth)(nil), "daprinternal.ComponentAuth")
	proto.RegisterType((*SaveStateEnvelope)(nil), "daprinternal.SaveStateEnvelope")
	proto.RegisterType((*KeyVal)(nil), "daprinternal.KeyVal")
	proto.RegisterType((*GetStateEnvelope)(nil), "daprinternal.GetStateEnvelope")
	proto.RegisterType((*PlacementOrder)(nil), "daprinternal.PlacementOrder")
	proto.RegisterType((*PlacementTables)(nil), "daprinternal.PlacementTables")
	proto.RegisterMapType((map[string]*PlacementTable)(nil), "daprinternal.PlacementTables.EntriesEntry")
	proto.RegisterType((*PlacementTable)(nil), "daprinternal.PlacementTable")
	proto.RegisterMapType((map[uint64]string)(nil), "daprinternal.PlacementTable.HostsEntry")
	proto.RegisterMapType((map[string]*Host)(nil), "daprinternal.PlacementTable.LoadMapEntry")
	proto.RegisterType((*Host)(nil), "daprinternal.Host")
}

func init() { proto.RegisterFile("daprinternal.proto", fileDescriptor_50527238b0452f75) }

var fileDescriptor_50527238b0452f75 = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xe1, 0x6e, 0xe3, 0x44,
	0x10, 0xae, 0x63, 0x37, 0xbd, 0x4c, 0x73, 0xbd, 0x76, 0x29, 0x47, 0xf1, 0x15, 0x5d, 0x64, 0x10,
	0x84, 0x4a, 0xb8, 0x10, 0x84, 0x74, 0xe2, 0x74, 0x42, 0x55, 0x9b, 0x3b, 0x42, 0x7b, 0x80, 0x36,
	0xc7, 0x89, 0x5f, 0x27, 0x6d, 0x9d, 0x69, 0x1b, 0x9d, 0xe3, 0xb5, 0xd6, 0x9b, 0x48, 0x79, 0x05,
	0xfe, 0xf3, 0x12, 0xbc, 0x04, 0x0f, 0xc0, 0x1b, 0x20, 0xf1, 0x0e, 0x3c, 0x02, 0xda, 0xf5, 0xda,
	0x59, 0x27, 0x4e, 0x2b, 0x7e, 0xdc, 0x2f, 0xaf, 0x67, 0xbf, 0x99, 0xf9, 0xe6, 0xf3, 0xec, 0xac,
	0x81, 0x8c, 0x58, 0x2a, 0xc6, 0x89, 0x44, 0x91, 0xb0, 0x38, 0x4c, 0x05, 0x97, 0x9c, 0xb4, 0x6d,
	0x9b, 0xff, 0xe1, 0x35, 0xe7, 0xd7, 0x31, 0x1e, 0xeb, 0xbd, 0xcb, 0xe9, 0xd5, 0x31, 0x4b, 0xe6,
	0x39, 0xd0, 0x7f, 0xb4, 0xbc, 0x85, 0x93, 0x54, 0x16, 0x9b, 0xef, 0xcd, 0x58, 0x3c, 0xc5, 0xec,
	0x38, 0x7f, 0xe4, 0xc6, 0xe0, 0x1f, 0x07, 0xf6, 0x2e, 0x78, 0xc4, 0xe2, 0x53, 0x16, 0xc7, 0xfd,
	0x64, 0x86, 0x31, 0x4f, 0x91, 0x74, 0xc1, 0x1b, 0x31, 0xc9, 0x0e, 0x9c, 0x8e, 0xd3, 0xdd, 0xee,
	0xed, 0x87, 0x79, 0xd8, 0xb0, 0x08, 0x1b, 0x9e, 0x24, 0x73, 0xaa, 0x11, 0xe4, 0x21, 0x34, 0x27,
	0x28, 0x6f, 0xf8, 0xe8, 0xa0, 0xd1, 0x71, 0xba, 0x2d, 0x6a, 0xde, 0xc8, 0x00, 0xee, 0x4d, 0x50,
	0x32, 0x1d, 0xc5, 0xed, 0xb8, 0xdd, 0xed, 0xde, 0x17, 0x61, 0xa5, 0xb2, 0x95, 0xa4, 0xe1, 0x4b,
	0x83, 0xef, 0x27, 0x52, 0xcc, 0x69, 0xe9, 0xee, 0x3f, 0x85, 0xfb, 0x95, 0x2d, 0xb2, 0x0b, 0xee,
	0x5b, 0x9c, 0x6b, 0x72, 0x2d, 0xaa, 0x96, 0x64, 0x1f, 0x36, 0x75, 0x55, 0x86, 0x44, 0xfe, 0xf2,
	0x6d, 0xe3, 0x89, 0x13, 0xfc, 0xde, 0x80, 0x3d, 0x95, 0xe5, 0x24, 0x92, 0x5c, 0x94, 0xf5, 0x1d,
	0xc0, 0x16, 0x53, 0x86, 0xc1, 0x99, 0x89, 0x52, 0xbc, 0x92, 0x43, 0x68, 0xe9, 0xe5, 0xab, 0x79,
	0x5a, 0x44, 0x5b, 0x18, 0xac, 0x6a, 0xdd, 0x4a, 0xb5, 0x85, 0x5e, 0xde, 0x9d, 0x7a, 0xd9, 0xba,
	0x6c, 0xd6, 0xe9, 0xb2, 0x42, 0xf6, 0xdd, 0xe8, 0xf2, 0xa7, 0x03, 0x3b, 0x83, 0x64, 0xc6, 0xdf,
	0x22, 0xc5, 0x2c, 0xe5, 0x49, 0xf6, 0x7f, 0x3e, 0xfa, 0x73, 0xab, 0x88, 0x86, 0x2e, 0xe2, 0xa8,
	0x5a, 0x44, 0x35, 0xf2, 0xbb, 0xa9, 0xe0, 0x0f, 0x07, 0x5a, 0xa7, 0x7c, 0x92, 0xf2, 0x04, 0x13,
	0x49, 0x9e, 0x5a, 0x94, 0xf2, 0x02, 0x1e, 0x2f, 0xe9, 0x5a, 0x40, 0x8b, 0x8c, 0x0b, 0x1e, 0xe4,
	0x18, 0xbc, 0x2c, 0xc5, 0x48, 0xe7, 0xd8, 0xee, 0x3d, 0x5a, 0xe3, 0x38, 0x4c, 0x31, 0xa2, 0x1a,
	0xa8, 0x1c, 0xd8, 0x54, 0xde, 0xe8, 0x2e, 0x58, 0xef, 0x70, 0x32, 0x95, 0x37, 0x54, 0x03, 0x83,
	0x3e, 0xec, 0xad, 0x10, 0x20, 0x04, 0xbc, 0x84, 0x4d, 0xd0, 0x94, 0xab, 0xd7, 0xaa, 0xff, 0xd4,
	0x33, 0x4b, 0x59, 0x54, 0xf6, 0x5f, 0x69, 0x08, 0xce, 0xe1, 0x7e, 0x85, 0x8e, 0x0a, 0x21, 0x55,
	0xa7, 0x9a, 0x10, 0x6a, 0x4d, 0x3e, 0x85, 0x66, 0xc4, 0x93, 0xab, 0xf1, 0xb5, 0xa9, 0x67, 0x27,
	0x34, 0x27, 0xfe, 0xb5, 0x7e, 0x50, 0xb3, 0x1b, 0xfc, 0xe6, 0xc0, 0xfb, 0x2b, 0xa4, 0x06, 0x12,
	0x27, 0xb5, 0xc4, 0x6a, 0x3f, 0x04, 0x79, 0x01, 0xed, 0x0c, 0x23, 0x81, 0xf2, 0x1c, 0xe7, 0x14,
	0xaf, 0x8c, 0x20, 0x1f, 0xaf, 0x53, 0xd0, 0x82, 0xd2, 0x8a, 0x63, 0xf0, 0xcc, 0xe2, 0x62, 0xc3,
	0x6a, 0xb9, 0x98, 0x36, 0x69, 0x94, 0x6d, 0x12, 0x7c, 0x65, 0x09, 0xa3, 0x64, 0x27, 0x1d, 0xd8,
	0xce, 0xe3, 0x0f, 0x25, 0x17, 0x85, 0xb7, 0x6d, 0x0a, 0xbe, 0x83, 0xbd, 0x21, 0x9b, 0xe1, 0x50,
	0x32, 0x89, 0xe5, 0x60, 0x38, 0x82, 0xcd, 0x4c, 0x19, 0x0e, 0x1c, 0xdd, 0xd6, 0xfb, 0xd5, 0x42,
	0xce, 0x71, 0xfe, 0x9a, 0xc5, 0x34, 0x87, 0x04, 0xcf, 0xa1, 0x99, 0x1b, 0x6a, 0xda, 0xf6, 0xc8,
	0x56, 0x6b, 0xdd, 0x61, 0xca, 0x21, 0xc1, 0x27, 0xb0, 0xfb, 0x42, 0x91, 0xb2, 0x79, 0xac, 0x44,
	0x0c, 0x10, 0x76, 0x7e, 0x8e, 0x59, 0x84, 0x13, 0x4c, 0xe4, 0x4f, 0x62, 0x84, 0x82, 0x7c, 0x03,
	0x4d, 0xc9, 0x2e, 0x63, 0xcc, 0x4c, 0xc3, 0x7f, 0x54, 0x25, 0x5b, 0xa2, 0x5f, 0x69, 0x10, 0x35,
	0x60, 0xd5, 0x61, 0x3c, 0x45, 0xc1, 0xe4, 0x98, 0x27, 0x45, 0x87, 0x95, 0x86, 0xe0, 0x2f, 0x07,
	0x1e, 0x2c, 0x79, 0x92, 0x33, 0xd8, 0xc2, 0x44, 0x8a, 0xb1, 0xce, 0x54, 0x73, 0xda, 0x97, 0xf0,
	0x61, 0x3f, 0x07, 0xe7, 0xa7, 0xbd, 0x70, 0x55, 0x33, 0x77, 0x86, 0x22, 0x5b, 0x64, 0x2d, 0x5e,
	0xfd, 0x5f, 0xa1, 0x6d, 0xbb, 0xd4, 0xc8, 0xd9, 0xab, 0xca, 0x79, 0x78, 0x5b, 0x7e, 0x7b, 0x46,
	0xfc, 0xdd, 0xb0, 0x54, 0xd3, 0xbb, 0xe4, 0x19, 0x6c, 0xde, 0xf0, 0x4c, 0x16, 0xa5, 0x7c, 0x76,
	0x5b, 0xa8, 0xf0, 0x7b, 0x85, 0xcc, 0xeb, 0xc8, 0xbd, 0x94, 0x7a, 0x19, 0x17, 0x12, 0x47, 0x43,
	0x94, 0x7a, 0xf6, 0x79, 0x74, 0x61, 0x20, 0xa7, 0xb0, 0x15, 0x73, 0x36, 0x7a, 0xc9, 0x52, 0x73,
	0xe9, 0x7d, 0x7e, 0x6b, 0xf8, 0x8b, 0x1c, 0x6b, 0x84, 0x32, 0x9e, 0x2a, 0x85, 0xe4, 0x92, 0xc5,
	0x6a, 0x57, 0xdf, 0x28, 0x2e, 0x5d, 0x18, 0xfc, 0x27, 0x00, 0x0b, 0x56, 0xb6, 0x54, 0xde, 0x1d,
	0x03, 0xd3, 0xff, 0x11, 0xda, 0x76, 0xc2, 0x1a, 0x99, 0xbb, 0x55, 0x99, 0x49, 0x95, 0xbc, 0x4a,
	0x6b, 0x8b, 0xfb, 0x06, 0x3c, 0x65, 0xaa, 0x3d, 0xa1, 0x04, 0xbc, 0x94, 0x0b, 0xa9, 0x03, 0xb9,
	0x54, 0xaf, 0x95, 0x4d, 0x95, 0xa8, 0x67, 0x84, 0x4b, 0xf5, 0x9a, 0xf8, 0x70, 0x0f, 0x13, 0x39,
	0x96, 0xaa, 0xb7, 0xbc, 0x8e, 0xdb, 0x6d, 0xd1, 0xf2, 0xbd, 0xf7, 0xaf, 0x03, 0xed, 0x33, 0x96,
	0x8a, 0x81, 0x21, 0x40, 0x2e, 0xa0, 0x55, 0xde, 0x8e, 0xe4, 0xf1, 0x1d, 0xd7, 0xa6, 0x7f, 0x78,
	0xdb, 0x95, 0x14, 0x6c, 0x14, 0xd1, 0xf4, 0x7f, 0xc8, 0x72, 0xb4, 0x95, 0x9f, 0x93, 0x3b, 0xa3,
	0x9d, 0xc1, 0x83, 0x5f, 0xd2, 0x11, 0x93, 0xb8, 0xb8, 0x92, 0x3e, 0x58, 0x33, 0x05, 0xfd, 0x87,
	0x2b, 0xd3, 0xa0, 0xaf, 0x7e, 0xd3, 0x82, 0x8d, 0xde, 0x1b, 0xd8, 0x2d, 0x5b, 0x64, 0x88, 0x62,
	0x36, 0x8e, 0x90, 0xfc, 0x00, 0xbb, 0x14, 0x95, 0x80, 0x4a, 0x0b, 0x35, 0x25, 0xa6, 0x19, 0xa9,
	0xf9, 0x32, 0xfe, 0xba, 0x43, 0xa1, 0x87, 0x45, 0xb0, 0xd1, 0x75, 0xbe, 0x74, 0x2e, 0x9b, 0x3a,
	0xe3, 0xd7, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xf7, 0xc1, 0x9c, 0x65, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaprInternalClient is the client API for DaprInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaprInternalClient interface {
	CallActor(ctx context.Context, in *CallActorEnvelope, opts ...grpc.CallOption) (*InvokeResponse, error)
	CallLocal(ctx context.Context, in *LocalCallEnvelope, opts ...grpc.CallOption) (*InvokeResponse, error)
	UpdateComponent(ctx context.Context, in *Component, opts ...grpc.CallOption) (*empty.Empty, error)
}

type daprInternalClient struct {
	cc *grpc.ClientConn
}

func NewDaprInternalClient(cc *grpc.ClientConn) DaprInternalClient {
	return &daprInternalClient{cc}
}

func (c *daprInternalClient) CallActor(ctx context.Context, in *CallActorEnvelope, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, "/daprinternal.DaprInternal/CallActor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprInternalClient) CallLocal(ctx context.Context, in *LocalCallEnvelope, opts ...grpc.CallOption) (*InvokeResponse, error) {
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, "/daprinternal.DaprInternal/CallLocal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprInternalClient) UpdateComponent(ctx context.Context, in *Component, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/daprinternal.DaprInternal/UpdateComponent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaprInternalServer is the server API for DaprInternal service.
type DaprInternalServer interface {
	CallActor(context.Context, *CallActorEnvelope) (*InvokeResponse, error)
	CallLocal(context.Context, *LocalCallEnvelope) (*InvokeResponse, error)
	UpdateComponent(context.Context, *Component) (*empty.Empty, error)
}

// UnimplementedDaprInternalServer can be embedded to have forward compatible implementations.
type UnimplementedDaprInternalServer struct {
}

func (*UnimplementedDaprInternalServer) CallActor(ctx context.Context, req *CallActorEnvelope) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallActor not implemented")
}
func (*UnimplementedDaprInternalServer) CallLocal(ctx context.Context, req *LocalCallEnvelope) (*InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallLocal not implemented")
}
func (*UnimplementedDaprInternalServer) UpdateComponent(ctx context.Context, req *Component) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComponent not implemented")
}

func RegisterDaprInternalServer(s *grpc.Server, srv DaprInternalServer) {
	s.RegisterService(&_DaprInternal_serviceDesc, srv)
}

func _DaprInternal_CallActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallActorEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprInternalServer).CallActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprinternal.DaprInternal/CallActor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprInternalServer).CallActor(ctx, req.(*CallActorEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprInternal_CallLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocalCallEnvelope)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprInternalServer).CallLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprinternal.DaprInternal/CallLocal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprInternalServer).CallLocal(ctx, req.(*LocalCallEnvelope))
	}
	return interceptor(ctx, in, info, handler)
}

func _DaprInternal_UpdateComponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Component)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprInternalServer).UpdateComponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daprinternal.DaprInternal/UpdateComponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprInternalServer).UpdateComponent(ctx, req.(*Component))
	}
	return interceptor(ctx, in, info, handler)
}

var _DaprInternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daprinternal.DaprInternal",
	HandlerType: (*DaprInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallActor",
			Handler:    _DaprInternal_CallActor_Handler,
		},
		{
			MethodName: "CallLocal",
			Handler:    _DaprInternal_CallLocal_Handler,
		},
		{
			MethodName: "UpdateComponent",
			Handler:    _DaprInternal_UpdateComponent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "daprinternal.proto",
}

// PlacementServiceClient is the client API for PlacementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlacementServiceClient interface {
	ReportDaprStatus(ctx context.Context, opts ...grpc.CallOption) (PlacementService_ReportDaprStatusClient, error)
}

type placementServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlacementServiceClient(cc *grpc.ClientConn) PlacementServiceClient {
	return &placementServiceClient{cc}
}

func (c *placementServiceClient) ReportDaprStatus(ctx context.Context, opts ...grpc.CallOption) (PlacementService_ReportDaprStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PlacementService_serviceDesc.Streams[0], "/daprinternal.PlacementService/ReportDaprStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &placementServiceReportDaprStatusClient{stream}
	return x, nil
}

type PlacementService_ReportDaprStatusClient interface {
	Send(*Host) error
	Recv() (*PlacementOrder, error)
	grpc.ClientStream
}

type placementServiceReportDaprStatusClient struct {
	grpc.ClientStream
}

func (x *placementServiceReportDaprStatusClient) Send(m *Host) error {
	return x.ClientStream.SendMsg(m)
}

func (x *placementServiceReportDaprStatusClient) Recv() (*PlacementOrder, error) {
	m := new(PlacementOrder)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PlacementServiceServer is the server API for PlacementService service.
type PlacementServiceServer interface {
	ReportDaprStatus(PlacementService_ReportDaprStatusServer) error
}

// UnimplementedPlacementServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlacementServiceServer struct {
}

func (*UnimplementedPlacementServiceServer) ReportDaprStatus(srv PlacementService_ReportDaprStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportDaprStatus not implemented")
}

func RegisterPlacementServiceServer(s *grpc.Server, srv PlacementServiceServer) {
	s.RegisterService(&_PlacementService_serviceDesc, srv)
}

func _PlacementService_ReportDaprStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PlacementServiceServer).ReportDaprStatus(&placementServiceReportDaprStatusServer{stream})
}

type PlacementService_ReportDaprStatusServer interface {
	Send(*PlacementOrder) error
	Recv() (*Host, error)
	grpc.ServerStream
}

type placementServiceReportDaprStatusServer struct {
	grpc.ServerStream
}

func (x *placementServiceReportDaprStatusServer) Send(m *PlacementOrder) error {
	return x.ServerStream.SendMsg(m)
}

func (x *placementServiceReportDaprStatusServer) Recv() (*Host, error) {
	m := new(Host)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _PlacementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daprinternal.PlacementService",
	HandlerType: (*PlacementServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportDaprStatus",
			Handler:       _PlacementService_ReportDaprStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "daprinternal.proto",
}
